/**
 * ⚠️  VENDORED FILE — govkit is NOT the owner of this code.
 *
 * Canonical source: https://github.com/techsilon-oss/release-gate-kit  (release-gate.ts)
 * Vendored version: recorded as `guardrails.release-gate.vendoredVersion` in govkit.json
 *
 * govkit carries a copy only so `/govkit-init` works offline and in one step. **Fix bugs and add
 * features upstream in release-gate-kit**, then re-vendor here and bump the recorded version — do
 * not patch this copy, or the two forks and the "one source of truth per concern" rule is broken
 * at exactly the layer that is supposed to enforce it.
 *
 * `/govkit-doctor` compares the RECORDED VERSION, deliberately not the file bytes: every project
 * runs its own formatter, so a byte comparison reports drift on every repo that uses Prettier,
 * gets ignored within a week, and then says nothing useful when the file genuinely diverges.
 */

/**
 * Local Release Gate (CI-fallback)
 * ────────────────────────────────────────────────────────────────────────────
 * A single local command that reproduces your CI checks, so you can keep
 * shipping at the same quality bar when CI is unavailable — e.g. the GitHub Free
 * Actions minutes cap (2,000/month, resets on the 1st) or any outage.
 *
 * Stack-agnostic and config-driven: the checks come from `release-gate.config.json`,
 * so this file drops into any project unchanged.
 *
 * Usage:
 *   npx tsx release-gate.ts [--full] [--pr <number>] [--base <ref>] [--config <path>]
 *
 *   --full            also run checks marked "full": true (e.g. E2E, Lighthouse)
 *   --pr <number>     post the evidence report as a comment on that PR (via `gh`)
 *   --base <ref>      value substituted for {{base}} in any check cmd (default origin/main)
 *   --config <path>   config file (default release-gate.config.json)
 *
 * Exit code: 0 if every RUN check passed; 1 if any run check failed. Skips are
 * not failures, so the gate is itself scriptable. Verify-only: never merges or
 * deploys. Requires Node 18+ and `tsx` (or compile to JS). `gh` only for --pr.
 *
 * License: public domain / CC0 — copy freely.
 */
import { spawnSync } from "child_process";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname } from "path";

export type Status = "pass" | "fail" | "skip";

export interface CheckResult {
  label: string;
  ciJob: string;
  status: Status;
  durationMs: number;
  detail: string;
}

export interface ReportMeta {
  timestamp: string;
  branch: string;
  base: string;
  sha: string;
  full: boolean;
}

interface CheckDef {
  /** Display name. */
  label: string;
  /** Optional CI-job label for the scorecard (defaults to `label`). */
  ciJob?: string;
  /** Shell command to run. `{{base}}` is replaced with the --base value. */
  cmd: string;
  /** Only run this check when --full is passed (e.g. browser-heavy suites). */
  full?: boolean;
  /** After running, augment the detail with counts from the junit file. */
  parseJunit?: boolean;
}

interface GateConfig {
  /** Path to a junit XML (for `parseJunit` checks). Default test-results/junit.xml. */
  junitPath?: string;
  /** Where to write the evidence report. Default test-results/release-gate-report.md. */
  reportPath?: string;
  checks: CheckDef[];
}

// ── Pure helpers (unit-testable) ─────────────────────────────────────────────

/** Reads `tests`/`failures` from the root <testsuites …> element (any attr order). */
export function parseJunitCounts(xml: string): { tests: number; failures: number } | null {
  const t = xml.match(/<testsuites[^>]*\btests="(\d+)"/);
  const f = xml.match(/<testsuites[^>]*\bfailures="(\d+)"/);
  if (t && f) return { tests: parseInt(t[1], 10), failures: parseInt(f[1], 10) };
  return null;
}

/** Verdict is ok iff no check FAILED. Skips don't count. */
export function computeVerdict(results: CheckResult[]): { ok: boolean; failed: string[] } {
  const failed = results.filter((r) => r.status === "fail").map((r) => r.label);
  return { ok: failed.length === 0, failed };
}

/** Markdown scorecard + verdict — the terminal output and the PR-comment body. */
export function renderReport(results: CheckResult[], meta: ReportMeta): string {
  const { ok, failed } = computeVerdict(results);
  const icon = (s: Status) => (s === "pass" ? "✅ PASS" : s === "fail" ? "❌ FAIL" : "⏭️ SKIPPED");
  const rows = results
    .map((r) => `| ${r.label} | ${r.ciJob} | ${icon(r.status)} | ${r.detail} |`)
    .join("\n");
  return [
    `## 🔐 Local Release Gate — ${ok ? "✅ GREEN" : "❌ RED"}`,
    "",
    "> Substitutes for CI during an outage / Actions-minutes cap. Generated by `npm run release-gate`.",
    "",
    `- **Commit:** \`${meta.sha}\` on \`${meta.branch}\` (base \`${meta.base}\`)`,
    `- **When:** ${meta.timestamp}`,
    `- **Mode:** ${meta.full ? "full" : "core (full-only checks skipped)"}`,
    "",
    "| Check | CI job | Result | Detail |",
    "|---|---|---|---|",
    rows,
    "",
    ok
      ? "**Verdict: GREEN — all run checks passed.**"
      : `**Verdict: RED — failed: ${failed.join(", ")}.**`,
    "",
  ].join("\n");
}

// ── Orchestration ────────────────────────────────────────────────────────────

function sh(cmd: string): { code: number; out: string } {
  const r = spawnSync(cmd, { shell: true, encoding: "utf-8", stdio: ["ignore", "pipe", "pipe"] });
  return { code: r.status ?? 1, out: (r.stdout || "") + (r.stderr || "") };
}

/** Returns trimmed stdout of a command, or "(no git)" if it fails (e.g. not a repo). */
function gitField(cmd: string): string {
  const r = spawnSync(cmd, { shell: true, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
  return r.status === 0 ? (r.stdout || "").trim() : "(no git)";
}

function loadConfig(path: string): GateConfig {
  if (!existsSync(path)) {
    console.error(`❌ Config not found: ${path}\n   Create a release-gate.config.json (see the README).`);
    process.exit(2);
  }
  const cfg = JSON.parse(readFileSync(path, "utf-8")) as GateConfig;
  if (!Array.isArray(cfg.checks) || cfg.checks.length === 0) {
    console.error(`❌ ${path} has no "checks" array.`);
    process.exit(2);
  }
  return cfg;
}

function main(): void {
  const args = process.argv.slice(2);
  const full = args.includes("--full");
  const prIdx = args.indexOf("--pr");
  const pr = prIdx >= 0 ? args[prIdx + 1] : null;
  const baseIdx = args.indexOf("--base");
  const base = baseIdx >= 0 && args[baseIdx + 1] ? args[baseIdx + 1] : "origin/main";
  const cfgIdx = args.indexOf("--config");
  const configPath = cfgIdx >= 0 && args[cfgIdx + 1] ? args[cfgIdx + 1] : "release-gate.config.json";

  const cfg = loadConfig(configPath);
  const junitPath = cfg.junitPath ?? "test-results/junit.xml";
  const reportPath = cfg.reportPath ?? "test-results/release-gate-report.md";

  console.log("\n🔐 Local Release Gate (CI-fallback)");
  console.log("=".repeat(64));

  const results: CheckResult[] = [];
  for (const c of cfg.checks) {
    const ciJob = c.ciJob ?? c.label;
    if (c.full && !full) {
      results.push({ label: c.label, ciJob, status: "skip", durationMs: 0, detail: "run --full" });
      console.log(`⏭️  ${c.label} — SKIPPED (run --full)`);
      continue;
    }
    const cmd = c.cmd.replace(/\{\{base\}\}/g, base);
    console.log(`\n▶ ${c.label}: ${cmd}`);
    const start = Date.now();
    const { code, out } = sh(cmd);
    const durationMs = Date.now() - start;
    const status: Status = code === 0 ? "pass" : "fail";
    let detail = code === 0 ? "ok" : `exit ${code}`;
    if (c.parseJunit && existsSync(junitPath)) {
      const j = parseJunitCounts(readFileSync(junitPath, "utf-8"));
      if (j) detail = `${j.tests} tests, ${j.failures} failures`;
    }
    results.push({ label: c.label, ciJob, status, durationMs, detail });
    console.log(
      `${status === "pass" ? "✅" : "❌"} ${c.label} — ${status.toUpperCase()} (${detail}, ${(durationMs / 1000).toFixed(0)}s)`,
    );
    if (status === "fail") console.log(out.split("\n").slice(-20).join("\n"));
  }

  const branch = gitField("git rev-parse --abbrev-ref HEAD");
  const sha = gitField("git rev-parse --short HEAD");
  const meta: ReportMeta = { timestamp: new Date().toISOString(), branch, base, sha, full };
  const report = renderReport(results, meta);

  const dir = dirname(reportPath);
  if (dir && !existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(reportPath, report);
  console.log("\n" + "=".repeat(64) + "\n" + report);
  console.log(`📄 Evidence written to ${reportPath}`);

  if (pr) {
    const r = sh(`gh pr comment ${pr} --body-file ${reportPath}`);
    console.log(r.code === 0 ? `💬 Evidence posted to PR #${pr}` : `⚠️  Failed to post PR comment:\n${r.out}`);
  }

  const { ok } = computeVerdict(results);
  console.log(`\n${ok ? "✅ GATE GREEN" : "❌ GATE RED"} — see ${reportPath}\n`);
  process.exit(ok ? 0 : 1);
}

// Run the CLI only when executed directly (not when imported by tests).
if (process.argv[1] && /release-gate(\.ts|\.js)?$/.test(process.argv[1].replace(/\\/g, "/"))) {
  main();
}
